USE TesteEvertecNew;
GO

ALTER TABLE dbo.CLIENTES
ADD CONSTRAINT FK_CLIENTES_CIDADES
FOREIGN KEY (ID_Cidade)
REFERENCES dbo.CIDADES(ID_Cidade);
GO

ALTER TABLE dbo.CLIENTES
ADD CONSTRAINT CK_CLIENTES_CPF_CNPJ
CHECK (CPF_CNPJ_Cliente <> '');
GO

ALTER TABLE dbo.CIDADES
ADD CONSTRAINT CK_CIDADES_CEP_FAIXA
CHECK (CEP_Final >= CEP_Inicial);
GO
